# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmToHcl < Formula
  desc "Utility for converting helm configuration to HCL for use in Terraform"
  homepage "https://github.com/mcwarman/helm-to-hcl/blob/main/README.md"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.1/helm-to-hcl_0.0.1_Darwin_arm64.tar.gz"
      sha256 "e9a265b78f39e7ea9567303bd15cbb82ed2f8a4c2c419fdcbaf7dd20de729094"

      def install
        bin.install "helm-to-hcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.1/helm-to-hcl_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "849138f44a1290ae32c2fa81143f0fa9b2b18e9302ec269922ed7bba198b5b16"

      def install
        bin.install "helm-to-hcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.1/helm-to-hcl_0.0.1_Linux_arm64.tar.gz"
      sha256 "c094a648ae22757a51848390963bd0ed74e07f4d644f48ee0308f517a5f6d6e9"

      def install
        bin.install "helm-to-hcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.1/helm-to-hcl_0.0.1_Linux_x86_64.tar.gz"
      sha256 "0c6930088da982ebb0f60ea97744f20262a3ee65d82eec9d9fb72ed941cdf9c6"

      def install
        bin.install "helm-to-hcl"
      end
    end
  end

  test do
    system "#{bin}/helm-to-hcl", "--version"
  end
end
