# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmToHcl < Formula
  desc "Utility for converting helm configuration to HCL for use in Terraform"
  homepage "https://github.com/mcwarman/helm-to-hcl/blob/main/README.md"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.4/helm-to-hcl_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "daff5ecc39ab475ba2f3558ee50c1bfc87d563e31da280fd474b4196e415166d"

      def install
        bin.install "helm-to-hcl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.4/helm-to-hcl_0.0.4_Darwin_arm64.tar.gz"
      sha256 "3e80789cc0499451c7d1143fcb55d7a24190961455bc21fdca11af2c2bafa8fe"

      def install
        bin.install "helm-to-hcl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.4/helm-to-hcl_0.0.4_Linux_arm64.tar.gz"
      sha256 "54f73ded8b632ab3e3c1d73602fb1cfb224abc077639bdd920d9144bce732563"

      def install
        bin.install "helm-to-hcl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mcwarman/helm-to-hcl/releases/download/v0.0.4/helm-to-hcl_0.0.4_Linux_x86_64.tar.gz"
      sha256 "18d8bf3a2495e799965a775ad6d9d484225890bd17a4317ea65045e7729de74e"

      def install
        bin.install "helm-to-hcl"
      end
    end
  end

  test do
    system "#{bin}/helm-to-hcl", "--version"
  end
end
